name: flutter_slides
description: Flutter Package to create presentations in Flutter for desktop.
version: 0.0.6
homepage: https://github.com/romaomb/flutter_slides

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: